# dev-user-kubeconfig.yaml
apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    certificate-authority-data: $CA_DATA
    server: $SERVER
contexts:
- name: dev-user-context
  context:
    cluster: my-cluster
    namespace: dev-namespace
    user: dev-user
users:
- name: dev-user
  user:
    token: $TOKEN
current-context: dev-user-context
